[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Note that `--connect-under-reset` was added to consistently reconnect to the target
runner = "probe-rs run --chip STM32F303VCT6 --connect-under-reset"

[build]
# Tell cargo to cross compile for the target architecture by default
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
